# Generated by Django 4.2.3 on 2023-07-10 21:58

from django.db import migrations, models
import parrotpayments.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('privileges', models.CharField(default='normal_user', max_length=255)),
                ('total_chars_used', models.IntegerField(default=0)),
                ('monthly_char_limit', models.IntegerField(default=4000)),
                ('monthly_chars_used', models.IntegerField(default=0)),
                ('char_credit', models.IntegerField(default=0)),
                ('last_char_reset', models.DateTimeField(default='1970-01-01 00:00:01')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', parrotpayments.managers.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
