# Generated by Django 4.1.4 on 2023-07-13 03:33

from django.db import migrations, models
import django.db.models.deletion
import parrotpayments.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('privileges', models.CharField(default='normal_user', max_length=255)),
                ('total_chars_used', models.IntegerField(default=0)),
                ('monthly_char_limit', models.IntegerField(default=4000)),
                ('monthly_chars_used', models.IntegerField(default=0)),
                ('char_credit', models.IntegerField(default=0)),
                ('last_char_reset', models.DateTimeField(default='1970-01-01 00:00:01')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('num_characters', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='SiteUsers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'siteusers',
            },
            managers=[
                ('objects', parrotpayments.managers.DiscordUserOAuth2Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('amount_paid', models.IntegerField(null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parrotpayments.products')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
