# Generated by Django 4.1.4 on 2023-07-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parrotpayments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_id',
            new_name='id',
        ),
    ]
