# Generated by Django 4.2.3 on 2023-07-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrotpayments', '0002_reloadoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reloadoptions',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
