# Generated by Django 4.1.4 on 2023-07-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrotpayments', '0002_rename_product_id_products_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='avatar',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
