# Generated by Django 4.1.4 on 2023-07-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrotpayments', '0003_alter_siteusers_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
